### ISSUE TITLE
Create setups

### ISSUE THREAD

**Issue by joshmreesjones** [twinitialize/billiards#11]
Create setups for:
- no collision
- glancing blow
- paradox

Each should be accessible by the main menu buttons.

**Comment by joshmreesjones** [comment]
Created setups infrastructure, now I need to make the setups actually make sense. It may be a good idea to finish the new background before I do that so I can position everything correctly.

**Comment by CarterPape** [comment]
Yeah, you should probably finish the new background before you do that.

**Comment by joshmreesjones** [comment]
Paradox setup is difficult, but I'll go with it.
